# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-12-10 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
